
CREATE TABLE issue_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    issue_id BIGINT NOT NULL,
    uploaded_by BIGINT NOT NULL,

    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(150),
    file_size BIGINT NOT NULL,
    storage_path VARCHAR(500) NOT NULL,

    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_attachment_issue
        FOREIGN KEY (issue_id)
        REFERENCES service_issues(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_attachment_user
        FOREIGN KEY (uploaded_by)
        REFERENCES app_users(id)
);